// Generated by scripts/split_v7_sketch.py from the locked v7 baseline; edit freely.
#include "commands.h"
#include "scanner.h"
#include "device_stats.h"
#include "hid_mode.h"
#include "hid_diag.h"

static void printHelp() {
  Serial.println();
  Serial.println("ESP32-S3 NimBLE Scanner");
  Serial.println("-----------------------");
  Serial.println("1 : start ACTIVE scan, quiet");
  Serial.println("2 : start PASSIVE scan, quiet");
  Serial.println("3 : start ACTIVE scan, verbose decoded packets");
  Serial.println("4 : start PASSIVE scan, verbose decoded packets");
  Serial.println("p : pause/resume");
  Serial.println("s : print summary now");
  Serial.println("i : print board / BLE stack information");
  Serial.println("m : toggle automatic 15 s summaries");
  Serial.println("v : toggle per-packet output");
  Serial.println("r : toggle raw hex");
  Serial.println("d : toggle AD decoding");
  Serial.println("u : toggle duplicate reports and restart");
  Serial.println("k : recycle scan/results");
  Serial.println("x : clear research statistics");
  Serial.println("+/- : adjust printed RSSI floor by 5 dB");
  Serial.println("b : BLE HID MODE - advertise as keyboard+mouse (Just Works pairing)");
  Serial.println("B : stop BLE HID mode");
  Serial.println("t : HID mouse-only diagnostic (NO keyboard report)");
  Serial.println("q : HID connection/subscription status");
  Serial.println("h or ? : show this menu");
  Serial.println();
}

static void printSystemInfo() {
  Serial.println();
  Serial.println("SYSTEM INFO");
  printBuildIdentity();
  Serial.printf("BLE stack: %s\n", BLEDevice::getBLEStackString().c_str());
  Serial.printf("CPU: %u MHz\n", (unsigned)getCpuFrequencyMhz());
  Serial.printf("Flash: %u bytes\n", (unsigned)ESP.getFlashChipSize());
  Serial.printf("Free heap: %u bytes\n", (unsigned)ESP.getFreeHeap());
  Serial.printf("PSRAM: %u bytes\n", (unsigned)ESP.getPsramSize());
#if defined(CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT)
  Serial.println("NimBLE BLE5 feature support: yes");
#else
  Serial.println("NimBLE BLE5 feature support: not exposed by this build");
#endif
#if defined(CONFIG_BT_NIMBLE_EXT_SCAN)
  Serial.println("Low-level NimBLE EXT_SCAN: enabled");
#else
  Serial.println("Low-level NimBLE EXT_SCAN: not enabled");
#endif
  Serial.printf("HID mode: %s connected=%s keyboard_sub=%s mouse_sub=%s\n",
                g_hidMode ? "active" : "off",
                g_hidConnected ? "yes" : "no",
                g_keyboardSubscribed ? "yes" : "no",
                g_mouseSubscribed ? "yes" : "no");
  Serial.println();
}

void handleCommand(char c) {
  switch (c) {
    case 'h':
    case 'H':
    case '?':
      printHelp();
      break;

    case '1':
      startPreset(true, false);
      break;

    case '2':
      startPreset(false, false);
      break;

    case '3':
      startPreset(true, true);
      break;

    case '4':
      startPreset(false, true);
      break;

    case 's':
    case 'S':
      printSummary();
      break;

    case 'i':
    case 'I':
      printSystemInfo();
      break;

    case 'm':
    case 'M':
      g_autoSummary = !g_autoSummary;
      Serial.printf("automatic summaries=%s\n", g_autoSummary ? "on" : "off");
      break;

    case 'v':
    case 'V':
      g_verbosePackets = !g_verbosePackets;
      Serial.printf("verbose=%s\n", g_verbosePackets ? "on" : "off");
      break;

    case 'r':
    case 'R':
      g_printRaw = !g_printRaw;
      Serial.printf("raw=%s\n", g_printRaw ? "on" : "off");
      break;

    case 'd':
    case 'D':
      g_decodeAD = !g_decodeAD;
      Serial.printf("decode=%s\n", g_decodeAD ? "on" : "off");
      break;

    case 'a':
    case 'A':
      g_activeScan = !g_activeScan;
      Serial.printf("activeScan=%s; restarting scanner...\n",
                    g_activeScan ? "on" : "off");
      restartScanner();
      break;

    case 'u':
    case 'U':
      g_keepDuplicates = !g_keepDuplicates;
      Serial.printf("duplicates=%s; restarting scanner...\n",
                    g_keepDuplicates ? "kept" : "filtered");
      restartScanner();
      break;

    case 'k':
    case 'K':
      Serial.println("Recycling scan/results...");
      restartScanner();
      break;

    case 'b':
      startHidMode();
      break;

    case 'B':
      stopHidMode();
      break;

    case 't':
    case 'T':
      sendHidTestInjection();
      break;

    case 'q':
    case 'Q':
      Serial.printf("[HID] mode=%s connected=%s keyboard_sub=%s mouse_sub=%s\n",
                    g_hidMode ? "yes" : "no",
                    g_hidConnected ? "yes" : "no",
                    g_keyboardSubscribed ? "yes" : "no",
                    g_mouseSubscribed ? "yes" : "no");
      break;

    case 'p':
    case 'P':
      if (g_paused || !g_scan->isScanning()) {
        Serial.println("Resuming scanner...");
        resumeScanner();
      } else {
        Serial.println("Pausing scanner...");
        stopScanner();
      }
      break;

    case 'x':
    case 'X':
      clearResearchStats();
      break;

    case '+':
      if (g_printRssiFloor < -5) {
        g_printRssiFloor += 5;
      }
      Serial.printf("print RSSI floor=%d dBm\n", (int)g_printRssiFloor);
      break;

    case '-':
      if (g_printRssiFloor > -127) {
        g_printRssiFloor -= 5;
        if (g_printRssiFloor < -127) g_printRssiFloor = -127;
      }
      Serial.printf("print RSSI floor=%d dBm\n", (int)g_printRssiFloor);
      break;

    case '\r':
    case '\n':
    case ' ':
    case '\t':
      break;

    default:
      Serial.printf("Unknown command '%c'. Press h for help.\n", c);
      break;
  }
}
