// Generated by scripts/split_v7_sketch.py from the locked v7 baseline; edit freely.
#include "hid_report_map.h"

// Composite HID report map: keyboard (report ID 1) + mouse (report ID 2).
// Standard Boot-Keyboard-compatible descriptors so Windows loads the
// built-in HID class driver without any vendor driver download.
const uint8_t HID_REPORT_MAP[] = {
  // --- Keyboard, report ID 1, 8-byte boot report ---
  0x05, 0x01,       // Usage Page (Generic Desktop)
  0x09, 0x06,       // Usage (Keyboard)
  0xA1, 0x01,       // Collection (Application)
  0x85, 0x01,       //   Report ID (1)
  0x05, 0x07,       //   Usage Page (Key Codes)
  0x19, 0xE0,       //   Usage Minimum (224 - LeftControl)
  0x29, 0xE7,       //   Usage Maximum (231 - RightGUI)
  0x15, 0x00,       //   Logical Minimum (0)
  0x25, 0x01,       //   Logical Maximum (1)
  0x75, 0x01,       //   Report Size (1)
  0x95, 0x08,       //   Report Count (8)
  0x81, 0x02,       //   Input (Data, Var, Abs) - modifier byte
  0x95, 0x01,       //   Report Count (1)
  0x75, 0x08,       //   Report Size (8)
  0x81, 0x01,       //   Input (Const) - reserved byte
  0x95, 0x06,       //   Report Count (6)
  0x75, 0x08,       //   Report Size (8)
  0x26, 0xFF, 0x00,  //   Logical Maximum (255)
  0x05, 0x07,       //   Usage Page (Key Codes)
  0x19, 0x00,       //   Usage Minimum (0)
  0x29, 0x91,       //   Usage Maximum (145)
  0x81, 0x00,       //   Input (Data, Array) - key array
  0xC0,             // End Collection

  // --- Mouse, report ID 2, 4-byte report (buttons + X + Y + wheel) ---
  0x05, 0x01,       // Usage Page (Generic Desktop)
  0x09, 0x02,       // Usage (Mouse)
  0xA1, 0x01,       // Collection (Application)
  0x85, 0x02,       //   Report ID (2)
  0x09, 0x01,       //   Usage (Pointer)
  0xA1, 0x00,       //   Collection (Physical)
  0x05, 0x09,       //     Usage Page (Buttons)
  0x19, 0x01,       //     Usage Minimum (1)
  0x29, 0x03,       //     Usage Maximum (3)
  0x15, 0x00,       //     Logical Minimum (0)
  0x25, 0x01,       //     Logical Maximum (1)
  0x75, 0x01,       //     Report Size (1)
  0x95, 0x03,       //     Report Count (3)
  0x81, 0x02,       //     Input (Data, Var, Abs) - buttons
  0x95, 0x01,       //     Report Count (1)
  0x75, 0x05,       //     Report Size (5)
  0x81, 0x01,       //     Input (Const) - padding
  0x05, 0x01,       //     Usage Page (Generic Desktop)
  0x09, 0x30,       //     Usage (X)
  0x09, 0x31,       //     Usage (Y)
  0x15, 0x81,       //     Logical Minimum (-127)
  0x25, 0x7F,       //     Logical Maximum (127)
  0x75, 0x08,       //     Report Size (8)
  0x95, 0x02,       //     Report Count (2)
  0x81, 0x06,       //     Input (Data, Var, Rel) - X, Y
  0x09, 0x38,       //     Usage (Wheel)
  0x15, 0x81,       //     Logical Minimum (-127)
  0x25, 0x7F,       //     Logical Maximum (127)
  0x75, 0x08,       //     Report Size (8)
  0x95, 0x01,       //     Report Count (1)
  0x81, 0x06,       //     Input (Data, Var, Rel) - wheel
  0xC0,             //   End Collection (Physical)
  0xC0              // End Collection
};

const size_t HID_REPORT_MAP_LEN = sizeof(HID_REPORT_MAP);
