// Generated by scripts/split_v7_sketch.py from the locked v7 baseline; edit freely.
#include "packet_queue.h"

static PacketSnapshot g_queue[PACKET_QUEUE_LEN];
static volatile size_t g_queueHead = 0;
static volatile size_t g_queueTail = 0;
volatile uint32_t g_queueDrops = 0;
static portMUX_TYPE g_queueMux = portMUX_INITIALIZER_UNLOCKED;

void clearPacketQueue() {
  portENTER_CRITICAL(&g_queueMux);
  g_queueHead = 0;
  g_queueTail = 0;
  g_queueDrops = 0;
  portEXIT_CRITICAL(&g_queueMux);
}

// Ring buffer
// ============================================================================

bool enqueuePacket(const PacketSnapshot& packet) {
  bool ok = false;

  portENTER_CRITICAL(&g_queueMux);

  const size_t next = (g_queueHead + 1) % PACKET_QUEUE_LEN;

  if (next != g_queueTail) {
    g_queue[g_queueHead] = packet;
    g_queueHead = next;
    ok = true;
  } else {
    ++g_queueDrops;
  }

  portEXIT_CRITICAL(&g_queueMux);

  return ok;
}

bool dequeuePacket(PacketSnapshot& packet) {
  bool ok = false;

  portENTER_CRITICAL(&g_queueMux);

  if (g_queueTail != g_queueHead) {
    packet = g_queue[g_queueTail];
    g_queueTail = (g_queueTail + 1) % PACKET_QUEUE_LEN;
    ok = true;
  }

  portEXIT_CRITICAL(&g_queueMux);

  return ok;
}
