"""One-time mechanical split of the monolithic v7 sketch into modules.

Reads the locked baseline (never modified) and writes module files into
firmware/BLEScanner_WORKING_v7/. Code bodies are copied verbatim by original
line range; only `static` linkage on cross-module symbols is removed and
double-spaced blank lines are collapsed. Hand-written glue (headers, globals
that now live in their owning module) is declared below.

Usage: python scripts/split_v7_sketch.py --force

Already applied on 2026-09-27; the modules have since been edited by hand, so
rerunning discards those edits. Kept for provenance of the mechanical split.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "evidence/baseline-v7/BLEScanner_LOCKED_BASELINE_v7.ino"
EXPECTED_SHA = "9f3c9099a50d7b83f9ff219d1a83767ffc319d4119f76e21b4088682a84914c6"
OUT = ROOT / "firmware/BLEScanner_WORKING_v7"


def load() -> list[str]:
    data = SOURCE.read_bytes()
    sha = hashlib.sha256(data).hexdigest()
    if sha != EXPECTED_SHA:
        raise SystemExit(f"baseline hash mismatch: {sha}")
    return data.decode("utf-8").replace("\r\n", "\n").split("\n")


if "--force" not in __import__("sys").argv and (OUT / "hid_mode.cpp").exists():
    raise SystemExit("modules already exist and contain hand edits; pass --force to overwrite")

LINES = load()


def rng(a: int, b: int) -> list[str]:
    """Original 1-based inclusive line range."""
    return LINES[a - 1 : b]


def collapse(lines: list[str]) -> list[str]:
    """Drop single blank lines (double-spacing artefact); keep one for runs >= 2."""
    out: list[str] = []
    i = 0
    while i < len(lines):
        if lines[i].strip():
            out.append(lines[i].rstrip())
            i += 1
            continue
        j = i
        while j < len(lines) and not lines[j].strip():
            j += 1
        if j - i >= 2 and out:
            out.append("")
        i = j
    while out and not out[-1]:
        out.pop()
    return out


def export(lines: list[str], names: list[str]) -> tuple[list[str], list[str]]:
    """Remove `static` from the named top-level functions; return prototypes."""
    protos: list[str] = []
    found: set[str] = set()
    result = []
    for line in lines:
        m = re.match(r"^static (.*?\b(\w+)\(.*\))\s*\{$", line)
        if m and m.group(2) in names:
            line = line[len("static "):]
            protos.append(m.group(1) + ";")
            found.add(m.group(2))
        result.append(line)
    missing = set(names) - found
    if missing:
        raise SystemExit(f"exports not found: {sorted(missing)}")
    return result, protos


def write(name: str, text: str) -> None:
    (OUT / name).write_text(text.rstrip() + "\n", encoding="utf-8", newline="\n")


BANNER = "// Generated by scripts/split_v7_sketch.py from the locked v7 baseline; edit freely.\n"


def module(cpp: str, header: str, doc: str, includes: list[str], body: list[str],
           exports: list[str], extra_header: str = "", globals_: str = "") -> None:
    body = collapse(body)
    body, protos = export(body, exports)
    inc = "\n".join(f'#include "{i}"' for i in [header] + includes)
    write(cpp, f"{BANNER}{inc}\n\n{globals_}{chr(10).join(body)}\n")
    guard = header.upper().replace(".", "_")
    write(header,
          f"// {doc}\n#pragma once\n\n#include \"config.h\"\n\n{extra_header}"
          + "\n".join(protos) + "\n")


# ---------------------------------------------------------------- config.h
write("config.h",
      "// Build requirements, includes and compile-time constants shared by every module.\n"
      "#pragma once\n\n"
      + "\n".join(collapse(rng(139, 222))) + "\n\n"
      "#include \"scan_types.h\"\n")
# scan_types.h must not include config.h recursively before constants exist.
write("scan_types.h",
      "// Plain data records passed between scanner, queue and statistics modules.\n"
      "#pragma once\n\n#include \"config.h\"\n\n"
      + "\n".join(collapse(rng(260, 390))) + "\n")

# ---------------------------------------------------------------- ble_format
module("ble_format.cpp", "ble_format.h",
       "Address, hex, UUID, company and advertising-type formatting helpers (pure, no state).",
       [], rng(600, 997),
       ["sameAddress", "printAddress", "addrTypeName", "randomAddrSubtype", "printHex",
        "le16", "le32", "be16", "be32", "fnv1a32", "printEscapedText", "printUUID128",
        "uuid16Name", "companyName", "printUUID16List", "printUUID32List", "advTypeName"])

# ---------------------------------------------------------------- ad_decoder
module("ad_decoder.cpp", "ad_decoder.h",
       "Advertising-data (AD structure) decoding: iBeacon, Eddystone, flags, identity extraction.",
       ["ble_format.h"], rng(998, 1977),
       ["extractIdentity", "decodeAD"])

# ---------------------------------------------------------------- packet_queue
module("packet_queue.cpp", "packet_queue.h",
       "ISR/callback-safe ring buffer of captured advertising packets (scanner -> loop).",
       [], rng(1980, 2056),
       ["enqueuePacket", "dequeuePacket"],
       extra_header="extern volatile uint32_t g_queueDrops;  // owned here; read-only elsewhere\n\n"
                    "void clearPacketQueue();\n",
       globals_="static PacketSnapshot g_queue[PACKET_QUEUE_LEN];\n"
                "static volatile size_t g_queueHead = 0;\n"
                "static volatile size_t g_queueTail = 0;\n"
                "volatile uint32_t g_queueDrops = 0;\n"
                "static portMUX_TYPE g_queueMux = portMUX_INITIALIZER_UNLOCKED;\n\n"
                "void clearPacketQueue() {\n"
                "  portENTER_CRITICAL(&g_queueMux);\n"
                "  g_queueHead = 0;\n  g_queueTail = 0;\n  g_queueDrops = 0;\n"
                "  portEXIT_CRITICAL(&g_queueMux);\n}\n\n")

# ---------------------------------------------------------------- device_stats
module("device_stats.cpp", "device_stats.h",
       "Per-device research statistics, packet display and the summary report.",
       ["ble_format.h", "ad_decoder.h", "packet_queue.h", "scanner.h", "hid_mode.h"],
       rng(2058, 2468) + ["", ""] + rng(3185, 3415) + ["", ""] + rng(3423, 3455),
       ["processPacket", "printSummary", "clearResearchStats"],
       extra_header="extern DeviceStats g_stats[MAX_TRACKED];  // owned here\n"
                    "extern uint64_t g_totalReports;\n"
                    "extern uint32_t g_statsDrops;\n"
                    "extern uint32_t g_lastSummaryMs;\n\n",
       globals_="DeviceStats g_stats[MAX_TRACKED];\n"
                "uint64_t g_totalReports = 0;\n"
                "uint32_t g_statsDrops = 0;\n"
                "uint32_t g_lastSummaryMs = 0;\n\n")

p = OUT / "device_stats.cpp"
_t = p.read_text(encoding="utf-8")
_old = re.search(r"  portENTER_CRITICAL\(&g_queueMux\);.*?portEXIT_CRITICAL\(&g_queueMux\);\n", _t, re.S)
if not _old:
    raise SystemExit("clearResearchStats queue block not found")
p.write_text(_t.replace(_old.group(0), "  clearPacketQueue();\n"), encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- scanner
module("scanner.cpp", "scanner.h",
       "BLE scan control: runtime scan options, NimBLE callbacks, finite scan slices, presets.",
       ["packet_queue.h", "hid_mode.h"],
       rng(2470, 2568) + ["", ""] + rng(3035, 3183) + ["", ""] + rng(3511, 3567),
       ["startScanSlice", "stopScanner", "resumeScanner", "restartScanner", "startPreset"],
       extra_header="// Runtime controls (owned here; commands.cpp toggles them).\n"
                    "extern bool g_activeScan;\nextern bool g_keepDuplicates;\n"
                    "extern bool g_verbosePackets;\nextern bool g_printRaw;\n"
                    "extern bool g_decodeAD;\nextern bool g_paused;\n"
                    "extern int8_t g_printRssiFloor;\nextern bool g_autoSummary;\n\n"
                    "extern BLEScan* g_scan;\nextern volatile bool g_scanSliceEnded;\n"
                    "extern uint32_t g_scanSlices;\nextern uint32_t g_scanStartFailures;\n\n",
       globals_="\n".join(re.sub(r"^static ", "", l) for l in collapse(rng(234, 248))) + "\n\n"
                "BLEScan* g_scan = nullptr;\nvolatile bool g_scanSliceEnded = false;\n"
                "uint32_t g_scanSlices = 0;\nuint32_t g_scanStartFailures = 0;\n\n")

# ---------------------------------------------------------------- hid_report_map
module("hid_report_map.cpp", "hid_report_map.h",
       "Composite HID report map bytes: keyboard report ID 1, mouse report ID 2.",
       [], [re.sub(r"^static const", "const", l) for l in rng(468, 594)], [],
       extra_header="extern const uint8_t HID_REPORT_MAP[];\nextern const size_t HID_REPORT_MAP_LEN;\n",
       globals_="")
p = OUT / "hid_report_map.cpp"
p.write_text(p.read_text(encoding="utf-8") + "\nconst size_t HID_REPORT_MAP_LEN = sizeof(HID_REPORT_MAP);\n",
             encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- hid_mode
module("hid_mode.cpp", "hid_mode.h",
       "BLE HID peripheral: GATT/HID construction, connection+subscription tracking, mouse-only test.",
       ["hid_report_map.h", "scanner.h"],
       rng(2570, 3033),
       ["startHidMode", "stopHidMode", "sendHidTestInjection"],
       extra_header="// HID state (owned here; read-only elsewhere).\n"
                    "extern bool g_hidMode;\nextern bool g_hidConnected;\n"
                    "extern volatile bool g_keyboardSubscribed;\nextern volatile bool g_mouseSubscribed;\n\n",
       globals_="bool g_hidMode = false;      // 'b' entered HID mode\n"
                "static bool g_hidBuilt = false;     // HID server has been constructed once\n"
                "bool g_hidConnected = false;\n"
                "static BLEServer* g_hidServer = nullptr;\n"
                "static BLEHIDDevice* g_hid = nullptr;\n"
                "static BLECharacteristic* g_keyboardInput = nullptr;\n"
                "static BLECharacteristic* g_mouseInput = nullptr;\n"
                "volatile bool g_keyboardSubscribed = false;\n"
                "volatile bool g_mouseSubscribed = false;\n\n")
p = OUT / "hid_mode.cpp"
p.write_text(p.read_text(encoding="utf-8").replace(
    "const_cast<uint8_t*>(HID_REPORT_MAP), sizeof(HID_REPORT_MAP)",
    "const_cast<uint8_t*>(HID_REPORT_MAP), HID_REPORT_MAP_LEN"), encoding="utf-8", newline="\n")

# ---------------------------------------------------------------- commands
module("commands.cpp", "commands.h",
       "Serial command dispatcher, help menu and system info (user-facing command contract).",
       ["scanner.h", "device_stats.h", "hid_mode.h"],
       rng(3457, 3509) + ["", ""] + rng(3569, 3897),
       ["handleCommand"])

# ---------------------------------------------------------------- main sketch
main = (collapse(rng(1, 135)) + ["", '#include "config.h"', '#include "packet_queue.h"',
        '#include "device_stats.h"', '#include "scanner.h"', '#include "commands.h"', "",
        "// Module map: see firmware/BLEScanner_WORKING_v7/MODULES.md", ""]
        + collapse(rng(3899, 4017)))
write("BLEScanner_WORKING_v7.ino", "\n".join(main))
print("split complete")
